info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  gorm:
    failOnError: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: saleshand7@gmail.com
    password: kewe cijo jspn xedl
    props:
      "mail.smtp.auth": "true"
      "mail.smtp.socketFactory.port": "465"
      "mail.smtp.socketFactory.class": "javax.net.ssl.SSLSocketFactory"
      "mail.smtp.socketFactory.fallback": "false"
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: html
dataSource:
  url: jdbc:postgresql://localhost:5432/salesmanagerdb
  driverClassName: org.postgresql.Driver
  username: 'postgres'
  password: 'pos123'
  pooled: true
  jmxExport: true
  dbCreate: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  cache:
    queries: true
    show_sql: true
    format_sql: true
    use_second_level_cache: false
    use_query_cache: false
server:
  port: 8080
  address: 0.0.0.0    
