info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  gorm:
    failOnError: true
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: html
dataSource:
  url: jdbc:postgresql://localhost:5432/SalesManagerDB
  driverClassName: org.postgresql.Driver
  username: 'postgres'
  password: 'password'
  pooled: true
  jmxExport: true
  dbCreate: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
